### ISSUE TITLE
Some blocks (slabs) within same blockspace should combine

### ISSUE THREAD

**Issue by therealtkh** [hea3ven/BuildingBricks#11]
Vanilla Minecraft behavior is that two slabs of the same type can be placed within the same block space. It will look like a block, but when broken, two slabs fall to the ground. 

This is not possible with BuildingBricks slabs. Not very important since for the most of the time, one could use blocks instead. But take a look at the vanilla, the texture looks quite nice when stacking the slab. I think it's called "double stone slab"? As said, not critical, but it's an expected behavior I think. I could accept that the full block version is dropped on the ground though (instead of two slabs).

Perhaps not as important for other block types, since they don't exist in vanilla or are not able to combine in such way anyway.

Oh and btw, smooth stone slabs are already in the game, but they have a different texture. And when I tried to look up the recipe for the double stone slab to confirm (with NEI, which works just fine with all other blocks I've tested in the mod), my client crashes :) Don't know if I should blame NEI or if there's a conflicting recipe causing it. Just a FYI.

**Comment by hea3ven** [comment]
Yeah, converting blocks is something I've been putting it off since it is non trivial, but it's planned.

About the double stone slabs, I'm modifying their recipe because it conflicts with how the rest of the slabs are crafted. Right now, their recipe is smelting smooth stone slabs in a furnace, which I'm not 100% sold on, so suggestions are welcomed. The crash is probably my fault, so if you don't mind, post it here.

**Comment by therealtkh** [comment]
Too late right now for smart suggestions, but I'll think about it.

Here's the crash report for the NEI check recipe on Double Stone Slabs:
http://pastebin.com/iDZpXyHv

**Comment by hea3ven** [comment]
Nvm, that recipe was the first idea I had, the actual recipe (which was wrongly set up and caused the crash) is 2 stone slabs => 2 double stone slabs.
